---

# access for master
- name: Generating master key for ec2-user
  user: "name={{amazon_user}} generate_ssh_key=yes"
  delegate_to: "{{master_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: register master pub key
  shell: "cat ~/.ssh/id_rsa.pub"
  delegate_to: "{{master_public_ip}}"
  remote_user: "{{amazon_user}}"
  register: "master_rsa_pub"

- name: install master pub key on bastion
  authorized_key: user="{{amazon_user}}" key="{{ master_rsa_pub.stdout }}"
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  with_items:
   - "{{bastion_public_ip}}"

- name: install master pub key on nodes
  authorized_key: user="{{amazon_user}}" key="{{ master_rsa_pub.stdout }}"
  delegate_to: "{{item.public_ip}}"
  remote_user: "{{amazon_user}}"
  with_items:
   - "{{nodes}}"

# access for bastion
- name: Generating bastion key for ec2-user
  user: "name={{amazon_user}} generate_ssh_key=yes"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: register bastion pub key
  shell: "cat ~/.ssh/id_rsa.pub"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  register: "bastion_rsa_pub"

- name: install bastion pub key on master
  authorized_key: user="{{amazon_user}}" key="{{ bastion_rsa_pub.stdout }}"
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  with_items:
   - "{{master_public_ip}}"

- name: install bastion pub key on nodes
  authorized_key: user="{{amazon_user}}" key="{{ bastion_rsa_pub.stdout }}"
  delegate_to: "{{item.public_ip}}"
  remote_user: "{{amazon_user}}"
  with_items:
   - "{{nodes}}"

- name: touch host known_hosts file on bastion
  file:
    path: ~/.ssh/known_hosts
    state: touch
    mode: "0644"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: run ssh-keyscan to add master to known_hosts
  command: /usr/bin/ssh-keyscan -t rsa {{ master_private_dns_name }} >> ~/.ssh/known_hosts
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: run ssh-keyscan to add nodes to known_hosts
  command: /usr/bin/ssh-keyscan -t rsa {{ item.private_dns_name }} >> ~/.ssh/known_hosts
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  with_items:
   - "{{nodes}}"

- name: touch host known_hosts file again, but add/remove some permissions
  file:
    path: ~/.ssh/known_hosts
    state: touch
    mode: "0600"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
